//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositoryParser.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RepositoryParser.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis of activity.
        /// </summary>
        public static string ActivityAnalyseButton {
            get {
                return ResourceManager.GetString("ActivityAnalyseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Chart.
        /// </summary>
        public static string ActivityChart {
            get {
                return ResourceManager.GetString("ActivityChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity List.
        /// </summary>
        public static string ActivityList {
            get {
                return ResourceManager.GetString("ActivityList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a repository.
        /// </summary>
        public static string AddRepositoryButton {
            get {
                return ResourceManager.GetString("AddRepositoryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis.
        /// </summary>
        public static string AnalysisButton {
            get {
                return ResourceManager.GetString("AnalysisButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyse:.
        /// </summary>
        public static string AnalysisWindowTitle {
            get {
                return ResourceManager.GetString("AnalysisWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes.
        /// </summary>
        public static string Changes {
            get {
                return ResourceManager.GetString("Changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis of activity of the repository users:.
        /// </summary>
        public static string ChartWindowTitle {
            get {
                return ResourceManager.GetString("ChartWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear the Data Base.
        /// </summary>
        public static string ClearDBButton {
            get {
                return ResourceManager.GetString("ClearDBButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string CommitsList_Author {
            get {
                return ResourceManager.GetString("CommitsList_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string CommitsList_Date {
            get {
                return ResourceManager.GetString("CommitsList_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string CommitsList_Email {
            get {
                return ResourceManager.GetString("CommitsList_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string CommitsList_ID {
            get {
                return ResourceManager.GetString("CommitsList_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string CommitsList_Message {
            get {
                return ResourceManager.GetString("CommitsList_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count of commits.
        /// </summary>
        public static string CountOfCommits {
            get {
                return ResourceManager.GetString("CountOfCommits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart of activity during days.
        /// </summary>
        public static string DayActivityChartChart {
            get {
                return ResourceManager.GetString("DayActivityChartChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of acitvity during days.
        /// </summary>
        public static string DayActivityChartList {
            get {
                return ResourceManager.GetString("DayActivityChartList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis of activity during days:.
        /// </summary>
        public static string DayActivityWindowTitle {
            get {
                return ResourceManager.GetString("DayActivityWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare.
        /// </summary>
        public static string DifferencesButton {
            get {
                return ResourceManager.GetString("DifferencesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparsion:.
        /// </summary>
        public static string DifferenceWindowTitle {
            get {
                return ResourceManager.GetString("DifferenceWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Succesed!.
        /// </summary>
        public static string ExportMessage {
            get {
                return ResourceManager.GetString("ExportMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string ExportTitle {
            get {
                return ResourceManager.GetString("ExportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to the File.
        /// </summary>
        public static string ExportToFileButton {
            get {
                return ResourceManager.GetString("ExportToFileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtering.
        /// </summary>
        public static string Filtering {
            get {
                return ResourceManager.GetString("Filtering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author:.
        /// </summary>
        public static string FilteringAuthor {
            get {
                return ResourceManager.GetString("FilteringAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        public static string FilteringDate {
            get {
                return ResourceManager.GetString("FilteringDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Content:.
        /// </summary>
        public static string FilteringMessage {
            get {
                return ResourceManager.GetString("FilteringMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Branch:.
        /// </summary>
        public static string FilteringPickBranch {
            get {
                return ResourceManager.GetString("FilteringPickBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Repository:.
        /// </summary>
        public static string FilteringPickRepository {
            get {
                return ResourceManager.GetString("FilteringPickRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours Analysis of activity.
        /// </summary>
        public static string HourActivityAnalyseButton {
            get {
                return ResourceManager.GetString("HourActivityAnalyseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart of activity during hours.
        /// </summary>
        public static string HoursActivityChartChart {
            get {
                return ResourceManager.GetString("HoursActivityChartChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of activity during hours.
        /// </summary>
        public static string HoursActivityChartList {
            get {
                return ResourceManager.GetString("HoursActivityChartList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis of activity during hours:.
        /// </summary>
        public static string HoursActivityWindowTitle {
            get {
                return ResourceManager.GetString("HoursActivityWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legend.
        /// </summary>
        public static string Legend {
            get {
                return ResourceManager.GetString("Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or pick from hard disc.
        /// </summary>
        public static string LocalAdress {
            get {
                return ResourceManager.GetString("LocalAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository Analyser.
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to January.
        /// </summary>
        public static string Month1 {
            get {
                return ResourceManager.GetString("Month1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to October.
        /// </summary>
        public static string Month10 {
            get {
                return ResourceManager.GetString("Month10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        public static string Month11 {
            get {
                return ResourceManager.GetString("Month11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to December.
        /// </summary>
        public static string Month12 {
            get {
                return ResourceManager.GetString("Month12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to February.
        /// </summary>
        public static string Month2 {
            get {
                return ResourceManager.GetString("Month2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March.
        /// </summary>
        public static string Month3 {
            get {
                return ResourceManager.GetString("Month3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        public static string Month4 {
            get {
                return ResourceManager.GetString("Month4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        public static string Month5 {
            get {
                return ResourceManager.GetString("Month5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to June.
        /// </summary>
        public static string Month6 {
            get {
                return ResourceManager.GetString("Month6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to July.
        /// </summary>
        public static string Month7 {
            get {
                return ResourceManager.GetString("Month7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to August.
        /// </summary>
        public static string Month8 {
            get {
                return ResourceManager.GetString("Month8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to September.
        /// </summary>
        public static string Month9 {
            get {
                return ResourceManager.GetString("Month9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis of month activity.
        /// </summary>
        public static string MonthActivityAnalyseButton {
            get {
                return ResourceManager.GetString("MonthActivityAnalyseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart of activity during months.
        /// </summary>
        public static string MonthActivityChartChart {
            get {
                return ResourceManager.GetString("MonthActivityChartChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of activity during months.
        /// </summary>
        public static string MonthActivityChartList {
            get {
                return ResourceManager.GetString("MonthActivityChartList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis of activity during months:.
        /// </summary>
        public static string MonthActivityWindowTitle {
            get {
                return ResourceManager.GetString("MonthActivityWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily analisys of activity.
        /// </summary>
        public static string MonthDayActivityAnalyseButton {
            get {
                return ResourceManager.GetString("MonthDayActivityAnalyseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ass.
        /// </summary>
        public static string myTitle {
            get {
                return ResourceManager.GetString("myTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Repository Path.
        /// </summary>
        public static string NoRepositoryPathError {
            get {
                return ResourceManager.GetString("NoRepositoryPathError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick the file.
        /// </summary>
        public static string PickFileButton {
            get {
                return ResourceManager.GetString("PickFileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick directory with repository..
        /// </summary>
        public static string PickFolderWithRepo {
            get {
                return ResourceManager.GetString("PickFolderWithRepo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string RefreshButton {
            get {
                return ResourceManager.GetString("RefreshButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send data.
        /// </summary>
        public static string SendDataButton {
            get {
                return ResourceManager.GetString("SendDataButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write the URL adress of the repository..
        /// </summary>
        public static string UrlAdress {
            get {
                return ResourceManager.GetString("UrlAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekday.
        /// </summary>
        public static string Weekday {
            get {
                return ResourceManager.GetString("Weekday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        public static string Weekday1 {
            get {
                return ResourceManager.GetString("Weekday1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        public static string Weekday2 {
            get {
                return ResourceManager.GetString("Weekday2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        public static string Weekday3 {
            get {
                return ResourceManager.GetString("Weekday3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        public static string Weekday4 {
            get {
                return ResourceManager.GetString("Weekday4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        public static string Weekday5 {
            get {
                return ResourceManager.GetString("Weekday5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string Weekday6 {
            get {
                return ResourceManager.GetString("Weekday6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        public static string Weekday7 {
            get {
                return ResourceManager.GetString("Weekday7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekdays Analysis of activity.
        /// </summary>
        public static string WeekdayActivityAnalyseButton {
            get {
                return ResourceManager.GetString("WeekdayActivityAnalyseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart of activity during weekdays.
        /// </summary>
        public static string WeekdayActivityChartChart {
            get {
                return ResourceManager.GetString("WeekdayActivityChartChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of activity during weekdays.
        /// </summary>
        public static string WeekdayActivityChartList {
            get {
                return ResourceManager.GetString("WeekdayActivityChartList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis of activity during weekdays:.
        /// </summary>
        public static string WeekdayActivityWindowTitle {
            get {
                return ResourceManager.GetString("WeekdayActivityWindowTitle", resourceCulture);
            }
        }
    }
}
